with-expecter: true
outpkg: mocks
dir: mocks
mockname: "{{.InterfaceName}}"
packages:
  xray-checker/internal/utils:
    # place your package-specific config here
    config:
    interfaces:
#      IPChecker: